version: '2.2'

networks:
  default:
    external:
      name: cyber-dojo

services:

  repl_container_python:
    build:
      context: server
      args:
        - CYBER_DOJO_RUNNER_HOME=${CYBER_DOJO_RUNNER_HOME}
        - PORT=${CYBER_DOJO_RUNNER_SERVICE_PORT}
    user: root
    image: cyberdojo/repl_container_python
    init: true
    container_name: repl_container_python
    read_only: false
    tmpfs: /tmp
    restart: 'no'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CYBER_DOJO_COVERAGE_ROOT
    ports:
      - ${CYBER_DOJO_RUNNER_SERVICE_PORT}:${CYBER_DOJO_RUNNER_SERVICE_PORT}
